
apiVersion: v1
kind: Service

metadata:
  name: bigdata-app-service

spec:
  type: NodePort

  selector:
    app: bigdata-app

  ports:
    - port: 5000
      targetPort: 5000
      nodePort: 30080
      protocol: TCP